**Exerise Question**
- Task 1: Try the algo on Dataset3 - OneHotEncoding of features and Train test Division 95%-5% 

In [70]:
#Step 1 Import Libraries
import numpy as np
import pandas as pd

In [71]:
df = pd.read_csv("Dataset3.csv")
print("\nData: \n", df)


Data: 
    Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [72]:
X= df.iloc[:, :-1]
y = df.iloc[:, -1].values

print("\nInputs: \n", X)
print("\nLabel: \n", y)


Inputs: 
    Outlook Temp Wind  Humidity
0        R    H    F         1
1        R    H    T         2
2        O    H    F         1
3        R    M    F         1
4        S    C    F         1
5        O    C    T         0
6        O    C    T         1
7        R    M    F         1
8        O    C    F         0
9        S    M    F         2
10       R    C    T         2
11       O    M    T         0
12       O    H    F         1
13       S    M    T         1

Label: 
 [0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [73]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()

In [74]:
outlook = onehotencoder.fit_transform(X.Outlook.values.reshape(-1,1)).toarray()
# print("\nInputs: \n", outlook)
temp = onehotencoder.fit_transform(X.Temp.values.reshape(-1,1)).toarray()
# print("\nInputs: \n", temp)
wind = onehotencoder.fit_transform(X.Wind.values.reshape(-1,1)).toarray()
# print("\nInputs: \n", wind)

In [75]:
#For Outlook
X_outlook = pd.DataFrame(outlook, columns=["Outlook_" + str(int (i)) for i in range(X.shape[1]-1)])
X = pd.concat([X, X_outlook], axis=1)
X = X.drop(['Outlook'], axis=1)

print("\nInput: \n", X)


Input: 
    Temp Wind  Humidity  Outlook_0  Outlook_1  Outlook_2
0     H    F         1        0.0        1.0        0.0
1     H    T         2        0.0        1.0        0.0
2     H    F         1        1.0        0.0        0.0
3     M    F         1        0.0        1.0        0.0
4     C    F         1        0.0        0.0        1.0
5     C    T         0        1.0        0.0        0.0
6     C    T         1        1.0        0.0        0.0
7     M    F         1        0.0        1.0        0.0
8     C    F         0        1.0        0.0        0.0
9     M    F         2        0.0        0.0        1.0
10    C    T         2        0.0        1.0        0.0
11    M    T         0        1.0        0.0        0.0
12    H    F         1        1.0        0.0        0.0
13    M    T         1        0.0        0.0        1.0


In [76]:
#For Temp
X_temp = pd.DataFrame(temp, columns=["Temp_" + str(int (i)) for i in range(X.shape[1]-3)])
X = pd.concat([X, X_temp], axis=1)
X = X.drop(['Temp'], axis=1)

print("\nInput: \n", X)


Input: 
    Wind  Humidity  Outlook_0  Outlook_1  Outlook_2  Temp_0  Temp_1  Temp_2
0     F         1        0.0        1.0        0.0     0.0     1.0     0.0
1     T         2        0.0        1.0        0.0     0.0     1.0     0.0
2     F         1        1.0        0.0        0.0     0.0     1.0     0.0
3     F         1        0.0        1.0        0.0     0.0     0.0     1.0
4     F         1        0.0        0.0        1.0     1.0     0.0     0.0
5     T         0        1.0        0.0        0.0     1.0     0.0     0.0
6     T         1        1.0        0.0        0.0     1.0     0.0     0.0
7     F         1        0.0        1.0        0.0     0.0     0.0     1.0
8     F         0        1.0        0.0        0.0     1.0     0.0     0.0
9     F         2        0.0        0.0        1.0     0.0     0.0     1.0
10    T         2        0.0        1.0        0.0     1.0     0.0     0.0
11    T         0        1.0        0.0        0.0     0.0     0.0     1.0
12    F        

In [77]:
#For Wind
X_wind = pd.DataFrame(wind, columns=["Wind_" + str(int (i)) for i in range(X.shape[1]-6)])
X = pd.concat([X, X_wind], axis=1)
X = X.drop(['Wind'], axis=1)

print("\nInput: \n", X)


Input: 
     Humidity  Outlook_0  Outlook_1  Outlook_2  Temp_0  Temp_1  Temp_2  Wind_0  \
0          1        0.0        1.0        0.0     0.0     1.0     0.0     1.0   
1          2        0.0        1.0        0.0     0.0     1.0     0.0     0.0   
2          1        1.0        0.0        0.0     0.0     1.0     0.0     1.0   
3          1        0.0        1.0        0.0     0.0     0.0     1.0     1.0   
4          1        0.0        0.0        1.0     1.0     0.0     0.0     1.0   
5          0        1.0        0.0        0.0     1.0     0.0     0.0     0.0   
6          1        1.0        0.0        0.0     1.0     0.0     0.0     0.0   
7          1        0.0        1.0        0.0     0.0     0.0     1.0     1.0   
8          0        1.0        0.0        0.0     1.0     0.0     0.0     1.0   
9          2        0.0        0.0        1.0     0.0     0.0     1.0     1.0   
10         2        0.0        1.0        0.0     1.0     0.0     0.0     0.0   
11         0      

In [78]:
X = X.values
print("\nInput: \n", X)


Input: 
 [[1. 0. 1. 0. 0. 1. 0. 1. 0.]
 [2. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [2. 0. 0. 1. 0. 0. 1. 1. 0.]
 [2. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 1.]]


In [79]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(X, y, test_size = 0.05, random_state = 128)

In [80]:
from sklearn.naive_bayes import GaussianNB

gaussiannb = GaussianNB()

gaussiannb.fit(data_train, target_train)

target_pred = gaussiannb.predict(data_test)
target_pred

array([1, 0, 0], dtype=int64)

In [81]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.6666666666666666


In [82]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[1, 0],
       [1, 1]], dtype=int64)

In [83]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.5 1. ]
recall: [1.  0.5]


**3.1 Questions for task-1**

In [84]:
#What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?
predicted= gaussiannb.predict([[1, 0, 1, 0, 0, 0, 1, 1, 0]]) # 0, 0, 1, 0, 0, 0, 1, 1, 0
print("Predicted Value:", predicted)

Predicted Value: [0]


In [85]:
#What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?
predicted= gaussiannb.predict([[2, 0, 0, 1, 1, 0, 0, 0, 1]]) # 2, 0, 0, 1, 1, 0, 0, 0, 1
print("Predicted Value:", predicted)

Predicted Value: [0]


**Exerise Question**
- Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 50-50%

In [86]:
from sklearn import datasets

wine = datasets.load_wine()

In [87]:
# print the names of the 13 features
print("Features: ", wine.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("\nLabels: ", wine.target_names)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

Labels:  ['class_0' 'class_1' 'class_2']


In [88]:
X1 = wine.data
y1 = wine.target

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 0.5, random_state=128)

In [89]:
gaussiannb = GaussianNB()

gaussiannb.fit(X_train1, y_train1)

target_pred1 = gaussiannb.predict(X_test1)
target_pred1

array([0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 1,
       1, 0, 2, 1, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 2, 1,
       0, 1, 0, 2, 2, 2, 1, 1, 2, 1, 1, 1, 0, 2, 0, 2, 1])

In [90]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test1, target_pred1))

Accuracy: 0.9672131147540983


In [91]:
confusion_matrix(y_test1, target_pred1)

array([[18,  2,  0],
       [ 0, 24,  0],
       [ 0,  0, 17]], dtype=int64)

In [92]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(y_test1, target_pred1, average=None)
recall = recall_score(y_test1, target_pred1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.92307692 1.        ]
recall: [0.9 1.  1. ]
